/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountForm: typeof import('./src/components/form/AccountForm.vue')['default']
    BackHeader: typeof import('./src/modules/mobile/components/BackHeader.vue')['default']
    BaseFooter: typeof import('./src/components/BaseFooter.vue')['default']
    BillCard: typeof import('./src/components/card/BillCard.vue')['default']
    DesktopHeader: typeof import('./src/modules/desktop/components/DesktopHeader.vue')['default']
    EmailForm: typeof import('./src/components/form/EmailForm.vue')['default']
    Fallback: typeof import('./src/components/Fallback.vue')['default']
    MobileFooter: typeof import('./src/modules/mobile/components/MobileFooter.vue')['default']
    MobileHeader: typeof import('./src/modules/mobile/components/MobileHeader.vue')['default']
    NativeDate: typeof import('./src/modules/mobile/components/NativeDate.vue')['default']
    NativeSelect: typeof import('./src/modules/mobile/components/NativeSelect.vue')['default']
    NoMessage: typeof import('./src/components/NoMessage.vue')['default']
    OrderCard: typeof import('./src/modules/mobile/components/OrderCard.vue')['default']
    PasswordForm: typeof import('./src/components/form/PasswordForm.vue')['default']
    PhoneForm: typeof import('./src/components/form/PhoneForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectService: typeof import('./src/modules/desktop/components/SelectService.vue')['default']
    ServiceGroupCard: typeof import('./src/components/card/ServiceGroupCard.vue')['default']
    ServiceItemCard: typeof import('./src/components/card/ServiceItemCard.vue')['default']
    SlideRight: typeof import('./src/modules/mobile/components/SlideRight.vue')['default']
    TheAvatar: typeof import('./src/components/TheAvatar.vue')['default']
    TheEmpty: typeof import('./src/components/TheEmpty.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheModal: typeof import('./src/modules/mobile/components/TheModal.vue')['default']
    TheSidebar: typeof import('./src/modules/desktop/components/TheSidebar.vue')['default']
    TheTheme: typeof import('./src/components/TheTheme.vue')['default']
    TicketCard: typeof import('./src/components/card/TicketCard.vue')['default']
    WechatForm: typeof import('./src/components/form/WechatForm.vue')['default']
    XBulletinBoard: typeof import('@3un/ui')['XBulletinBoard']
    XButton: typeof import('@3un/ui')['XButton']
    XDatePicker: typeof import('@3un/ui')['XDatePicker']
    XDialog: typeof import('@3un/ui')['XDialog']
    XInput: typeof import('@3un/ui')['XInput']
    XPagination: typeof import('@3un/ui')['XPagination']
    XPopover: typeof import('@3un/ui')['XPopover']
    XSegmented: typeof import('@3un/ui')['XSegmented']
    XSelect: typeof import('@3un/ui')['XSelect']
    XSelectGroup: typeof import('@3un/ui')['XSelectGroup']
    XSelectItem: typeof import('@3un/ui')['XSelectItem']
    XSimplePagination: typeof import('@3un/ui')['XSimplePagination']
    XSliderCaptcha: typeof import('@3un/ui')['XSliderCaptcha']
    XSwitch: typeof import('@3un/ui')['XSwitch']
    XTable: typeof import('@3un/ui')['XTable']
    XTag: typeof import('@3un/ui')['XTag']
    XTextarea: typeof import('@3un/ui')['XTextarea']
  }
}
