/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    DesktopHeader: typeof import('./src/modules/desktop/components/DesktopHeader.vue')['default']
    Fallback: typeof import('./src/components/Fallback.vue')['default']
    FormDialog: typeof import('./src/modules/desktop/components/FormDialog.vue')['default']
    FormField: typeof import('./src/modules/desktop/components/FormField.vue')['default']
    FormModal: typeof import('./src/modules/mobile/components/FormModal.vue')['default']
    MobileHeader: typeof import('./src/modules/mobile/components/MobileHeader.vue')['default']
    NativeSelectService: typeof import('./src/modules/mobile/components/NativeSelectService.vue')['default']
    NoMessage: typeof import('./src/components/NoMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPlane: typeof import('./src/modules/desktop/components/SearchPlane.vue')['default']
    SearchRouteItem: typeof import('./src/modules/desktop/components/SearchRouteItem.vue')['default']
    SelectAccesslevel: typeof import('./src/modules/desktop/components/SelectAccesslevel.vue')['default']
    SelectActivity: typeof import('./src/modules/desktop/components/SelectActivity.vue')['default']
    SelectIllustrate: typeof import('./src/modules/desktop/components/SelectIllustrate.vue')['default']
    SelectService: typeof import('./src/modules/desktop/components/SelectService.vue')['default']
    SettingPlane: typeof import('./src/modules/desktop/components/SettingPlane.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/SidebarItem.vue')['default']
    SlideRight: typeof import('./src/modules/mobile/components/SlideRight.vue')['default']
    SplitPlane: typeof import('./src/modules/desktop/components/SplitPlane.vue')['default']
    TheConfirm: typeof import('./src/components/TheConfirm.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheModal: typeof import('./src/modules/mobile/components/TheModal.vue')['default']
    TheTheme: typeof import('./src/components/TheTheme.vue')['default']
    TodoMsg: typeof import('./src/components/TodoMsg.vue')['default']
    Toolbar: typeof import('./src/modules/mobile/components/Toolbar.vue')['default']
    XBadge: typeof import('@3un/ui')['XBadge']
    XButton: typeof import('@3un/ui')['XButton']
    XButtonSplit: typeof import('@3un/ui')['XButtonSplit']
    XDialog: typeof import('@3un/ui')['XDialog']
    XInput: typeof import('@3un/ui')['XInput']
    XInputNumber: typeof import('@3un/ui')['XInputNumber']
    XNativeSelect: typeof import('@3un/ui')['XNativeSelect']
    XPopover: typeof import('@3un/ui')['XPopover']
    XSelect: typeof import('@3un/ui')['XSelect']
    XSelectGroup: typeof import('@3un/ui')['XSelectGroup']
    XSelectItem: typeof import('@3un/ui')['XSelectItem']
    XSimplePagination: typeof import('@3un/ui')['XSimplePagination']
    XSwitch: typeof import('@3un/ui')['XSwitch']
    XTextarea: typeof import('@3un/ui')['XTextarea']
  }
}
