/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountForm: typeof import('./src/components/forms/auth/AccountForm.vue')['default']
    QrcodeForm: typeof import('./src/components/forms/auth/QrcodeForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SanHe: typeof import('./src/components/logos/SanHe.vue')['default']
    TheEmpty: typeof import('./src/components/TheEmpty.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheTheme: typeof import('./src/components/TheTheme.vue')['default']
    XButton: typeof import('@3un/ui')['XButton']
    XInput: typeof import('@3un/ui')['XInput']
    XSegmented: typeof import('@3un/ui')['XSegmented']
  }
}
