/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheTheme: typeof import('./src/components/TheTheme.vue')['default']
    XButton: typeof import('@3un/ui')['XButton']
    XInput: typeof import('@3un/ui')['XInput']
  }
}
