/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonGroup: typeof import('./src/components/ButtonGroup.vue')['default']
    FallBack: typeof import('./src/components/FallBack.vue')['default']
    HistoryCard: typeof import('./src/components/cards/HistoryCard.vue')['default']
    OrderCard: typeof import('./src/components/cards/OrderCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectServices: typeof import('./src/modules/desktop/components/SelectServices.vue')['default']
    StoreCard: typeof import('./src/components/cards/StoreCard.vue')['default']
    TheBack: typeof import('./src/modules/desktop/components/TheBack.vue')['default']
    TheConfirm: typeof import('./src/components/TheConfirm.vue')['default']
    TheFooter: typeof import('./src/modules/desktop/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/modules/desktop/components/TheHeader.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheMainContain: typeof import('./src/modules/desktop/components/TheMainContain.vue')['default']
    XButton: typeof import('@3un/ui')['XButton']
    XDialog: typeof import('@3un/ui')['XDialog']
    XInput: typeof import('@3un/ui')['XInput']
    XSelect: typeof import('@3un/ui')['XSelect']
    XSelectGroup: typeof import('@3un/ui')['XSelectGroup']
    XSelectItem: typeof import('@3un/ui')['XSelectItem']
    XTag: typeof import('@3un/ui')['XTag']
    XTextarea: typeof import('@3un/ui')['XTextarea']
  }
}
