/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectService: typeof import('./src/components/SelectService.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TheEmpty: typeof import('./src/components/TheEmpty.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheTag: typeof import('./src/components/TheTag.vue')['default']
    TheTheme: typeof import('./src/components/TheTheme.vue')['default']
    XButton: typeof import('@3un/ui')['XButton']
    XDialog: typeof import('@3un/ui')['XDialog']
    XInput: typeof import('@3un/ui')['XInput']
    XPagination: typeof import('@3un/ui')['XPagination']
    XPopover: typeof import('@3un/ui')['XPopover']
    XSelect: typeof import('@3un/ui')['XSelect']
    XSelectGroup: typeof import('@3un/ui')['XSelectGroup']
    XSelectItem: typeof import('@3un/ui')['XSelectItem']
    XTag: typeof import('@3un/ui')['XTag']
    XTextarea: typeof import('@3un/ui')['XTextarea']
  }
}
